version: '3.8'

services:
  shopping-app:
    build: .
    container_name: shopping-app
    restart: always
    ports:
      - "3033:3000"
    volumes:
      - sqlite_data:/app/prisma/data
    environment:
      - DATABASE_URL=file:/app/prisma/data/dev.db
      - SIRI_SECRET=mein-geheimes-passwort
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shoppingapp.rule=Host(`liste.kochrakete.at`)"
      - "traefik.http.routers.shoppingapp.entrypoints=websecure"
      - "traefik.http.routers.shoppingapp.tls=true"
      # Usually the provider name here is letsencrypt or myresolver, but traefik often auto-detects if there's only one.
      - "traefik.http.routers.shoppingapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.shoppingapp.loadbalancer.server.port=3000"
      - "traefik.docker.network=root_default"
    networks:
      - root_default
      - default

networks:
  root_default:
    external: true

volumes:
  sqlite_data:

